name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Mintlify
        run: npm i -g mintlify

      - name: Check broken links
        run: mintlify broken-links

      - name: Run Vale linting
        uses: errata-ai/vale-action@reviewdog
        with:
          files: .
          fail_on_error: true

      - name: Validate OpenAPI specs
        run: mintlify openapi-check