name: Index docs

on:
  schedule:
    - cron: "0 */3 * * *"  

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install CLI
        run: npm install -g @team-plain/cli@latest
        
      - name: Index Docs
        run: plain index-sitemap https://mintlify.com/docs/sitemap.xml
        env:
          PLAIN_API_KEY: ${{ secrets.PLAIN_API_KEY }}
